[package]
name = "simple-phase-vocoder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.2"
hound = "3.5.1"
rustfft = "6.1.0"
